###############################
#
#       UCB-JUDGE - v1.0
#
###############################

version: "3.7"

networks:
  pocketnet:
    name: network-ucb-judge
    driver: bridge
  elk-ucb-judge:
    external: true

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    command: start-dev
    restart: always
    ports:
      - "8090:8090"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8090
    volumes:
      - ~/Desktop/SIS-311/ucb-judge/keycloak:/opt/keycloak/data
    networks:
      - pocketnet
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - pocketnet
  config-server:
    image: ucb-judge-config-server:1.0.2
    ports:
      - "8888:8888"
    environment:
      CONFIG_SERVER_USER: ${CONFIG_SERVER_USER}
      CONFIG_SERVER_PASSWORD: ${CONFIG_SERVER_PASSWORD}
      GIT_REPO_URI: ${GIT_REPO_URI}
      HOST_KEY: ${HOST_KEY}
      PRIVATE_KEY_PATH: ${PRIVATE_KEY_PATH}
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      LOGSTASH_SERVER_URI: ${LOGSTASH_SERVER_URI}
    volumes:
      - ~/Desktop/SIS-311/ucb-judge/config-server:/opt/ucb-judge/logs/uj-config-server
    networks:
      - pocketnet
      - elk-ucb-judge

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ~/Desktop/SIS-311/ucb-judge/minio:/data
    command: server /data --console-address ":9090"
    networks:
      - pocketnet
