###############################
#
#       UCB-JUDGE - v1.0
#
###############################

version: "3.7"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.0.1
    command: start-dev
    restart: always
    ports:
      - "8090:8090"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8090
    volumes:
      - /Users/chrisalanapazaaguilar/Desktop/SIS-311/ucb-judge/keycloak:/opt/keycloak/data
